/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ifmg.projeto_haras.view.veterinario;

import com.ifmg.estudojpa.model.auth.Autenticador;
import com.ifmg.projeto_haras.controller.EquinoController;
import com.ifmg.projeto_haras.controller.ServicoAdicionalController;
import com.ifmg.projeto_haras.controller.VeterinarioController;
import com.ifmg.projeto_haras.model.exceptions.EquinoException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class FrVeterinarioEqServico extends javax.swing.JFrame {

    private JFrame telaAnterior;
    EquinoController equinoController;
    ServicoAdicionalController servicoAdicionalController;
    VeterinarioController veterinarioController;
    /**
     * Creates new form FrVeterinarioEqServico
     */
    public FrVeterinarioEqServico(JFrame telaQueChamou) {
        telaAnterior = telaQueChamou;
        equinoController = new EquinoController();
        servicoAdicionalController = new ServicoAdicionalController();
        veterinarioController = new VeterinarioController();
        initComponents();
        
        equinoCombobox();
        servicoAdicionalCombobox();
        
        equinoController.atualizarTabelaRelacionamentosServicos(grdEquinosServicosAdicionais);
    }
    
    public void equinoCombobox() {
        String[] equinoString = veterinarioController.buscarEquinosString(Autenticador.getIdLogado()).split("\n");

        for (String equinoIdNome : equinoString) {
            cbxEquinos.addItem(equinoIdNome);
        }
    }
    
    public void servicoAdicionalCombobox() {
        String[] servicoString = servicoAdicionalController.buscarServicoAdicionalString().split("\n");

        for (String servicoIdNome : servicoString) {
            cbxServicosAdicionais.addItem(servicoIdNome);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        cbxEquinos = new javax.swing.JComboBox<>();
        lblEquinoCbx = new javax.swing.JLabel();
        lblServicoAdicionalCbx = new javax.swing.JLabel();
        cbxServicosAdicionais = new javax.swing.JComboBox<>();
        edtQuantidade = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdEquinosServicosAdicionais = new javax.swing.JTable();
        btnRelacionar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Relacionar Serviços adicionais");

        lblEquinoCbx.setText("Equino:");

        lblServicoAdicionalCbx.setText("Serviço adicional:");

        lblQuantidade.setText("Quatidade:");

        grdEquinosServicosAdicionais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(grdEquinosServicosAdicionais);

        btnRelacionar.setText("Relacionar");
        btnRelacionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelacionarActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxEquinos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEquinoCbx))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxServicosAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblServicoAdicionalCbx))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQuantidade))))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(btnRelacionar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(btnDeletar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEquinoCbx)
                    .addComponent(lblServicoAdicionalCbx)
                    .addComponent(lblQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxEquinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxServicosAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRelacionar)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeletar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelacionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelacionarActionPerformed
        String servico = String.valueOf(cbxServicosAdicionais.getSelectedItem());
        String equino = String.valueOf(cbxEquinos.getSelectedItem());
        
        if(!servico.equals("") && !equino.equals("")){
            try {
                equinoController.relacionarEquinoServico(equino, servico, edtQuantidade.getText());
            } catch (EquinoException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            
            equinoController.atualizarTabelaRelacionamentosServicos(grdEquinosServicosAdicionais);
        }
        
        // Atualizar tabela
    }//GEN-LAST:event_btnRelacionarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        deletarlinhaGrdSelecionada();
    }//GEN-LAST:event_btnDeletarActionPerformed

    
    private void deletarlinhaGrdSelecionada(){
        Object[] relSelecionado = (Object[]) this.getObjectSelectOnGrid();

        if (relSelecionado == null)
            JOptionPane.showMessageDialog(this, "Primeiro selecione um registro na tabela.");
        else {
            try {
                equinoController.excluirRelacionamentoServicos(
                        Integer.parseInt(relSelecionado[0].toString()), Integer.parseInt(relSelecionado[2].toString())
                );

                JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso!");
            } catch (EquinoException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        
        equinoController.atualizarTabelaRelacionamentosServicos(grdEquinosServicosAdicionais);
    }
    
    private Object getObjectSelectOnGrid() {
        int rowCliked = grdEquinosServicosAdicionais.getSelectedRow();
        Object obj = null;
        if (rowCliked >= 0) {
            obj = grdEquinosServicosAdicionais.getModel().getValueAt(rowCliked, -1);
        }
        return obj;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnRelacionar;
    private javax.swing.JComboBox<String> cbxEquinos;
    private javax.swing.JComboBox<String> cbxServicosAdicionais;
    private javax.swing.JTextField edtQuantidade;
    private javax.swing.JTable grdEquinosServicosAdicionais;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEquinoCbx;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblServicoAdicionalCbx;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
