/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ifmg.projeto_haras.view;

import com.ifmg.estudojpa.model.auth.Autenticador;
import com.ifmg.projeto_haras.controller.ProprietarioController;
import com.ifmg.projeto_haras.controller.RelFaturasController;
import com.ifmg.projeto_haras.controller.RelServicosController;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class FrProprietario extends javax.swing.JFrame {

    ProprietarioController proprietarioController;
    RelServicosController relServicosController;
    RelFaturasController relFaturasController;
    /**
     * Creates new form FrProprietario
     */
    public FrProprietario() {
        proprietarioController = new ProprietarioController();
        relServicosController = new RelServicosController();
        relFaturasController = new RelFaturasController();
        initComponents();
        
        proprietarioController.atualizarTabelaEquinos(grdEquinos, Autenticador.getIdLogado());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        grdEquinos = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        btnRelFaturas = new javax.swing.JButton();
        btnRelServicos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEquinos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grdEquinos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        grdEquinos.setEnabled(false);
        jScrollPane1.setViewportView(grdEquinos);

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Proprietário");

        btnRelFaturas.setText("Gerar");
        btnRelFaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelFaturasActionPerformed(evt);
            }
        });

        btnRelServicos.setText("Gerar");
        btnRelServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelServicosActionPerformed(evt);
            }
        });

        jLabel1.setText("Gerar relatório de serviços:");

        jLabel2.setText("Gerar relatório de faturas:");

        lblEquinos.setText("Equinos registrados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRelServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnRelFaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(lblEquinos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRelFaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(lblEquinos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelServicosActionPerformed
        
        if(relServicosController.gerarRelatorio(Autenticador.getIdLogado())){
            JOptionPane.showMessageDialog(this, "Relatório de Serviços Adicionais gerado com sucesso.");
        }
    }//GEN-LAST:event_btnRelServicosActionPerformed

    private void btnRelFaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelFaturasActionPerformed
        
        if(relFaturasController.gerarRelatorio(Autenticador.getIdLogado())){
            JOptionPane.showMessageDialog(this, "Relatório de Faturas gerado com sucesso.");
        }
    }//GEN-LAST:event_btnRelFaturasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRelFaturas;
    private javax.swing.JButton btnRelServicos;
    private javax.swing.JTable grdEquinos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEquinos;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
